version: "3"
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/nginx/vhost.d:/etc/nginx/vhost.d
      - /data/nginx/html:/usr/share/nginx/html
      - /data/certs:/etc/nginx/certs:ro
  generator:
    image: jwilder/docker-gen
    container_name: generator
    restart: always
    depends_on:
      - proxy
    volumes:
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/nginx/vhost.d:/etc/nginx/vhost.d
      - /data/nginx/html:/usr/share/nginx/html
      - /data/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /data/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    command: "-notify-sighup proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    depends_on:
      - generator
    volumes:
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/nginx/vhost.d:/etc/nginx/vhost.d
      - /data/nginx/html:/usr/share/nginx/html
      - /data/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=proxy
      - NGINX_DOCKER_GEN_CONTAINER=generator

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    links:
      - rabbit
      - mongo
    environment:
      - VIRTUAL_HOST=farm.openzim.org
      - LETSENCRYPT_HOST=farm.openzim.org
      - LETSENCRYPT_EMAIL=contact@kiwix.org
      - INIT_USERNAME=admin
      - INIT_PASSWORD=admin_pass
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - /data/mongo:/data/db
  rabbit:
    build:
      context: ./rabbit
      dockerfile: Dockerfile
    container_name: rabbit
    restart: always
    ports:
      - 5671:5671
      - 8080:15672
    volumes:
      - /data/certs/farm.openzim.org:/certs
      - /data/rabbit:/var/lib/rabbitmq