name: Healthcheck QA

on:
  pull_request:
    paths:
      - "healthcheck/**"
  push:
    paths:
      - "healthcheck/**"
    branches:
      - main

jobs:
  check-qa:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: healthcheck/pyproject.toml
          architecture: x64

      - name: Install dependencies (and project)
        working-directory: healthcheck
        run: |
          pip install -U pip
          pip install -e .[lint,scripts,test,check]

      - name: Check black formatting
        working-directory: healthcheck
        run: inv lint-black

      - name: Check ruff
        working-directory: healthcheck
        run: inv lint-ruff

      - name: Check pyright
        working-directory: healthcheck
        run: inv check-pyright
